### ISSUE TITLE
您好，启用了以后不生效

### ISSUE THREAD

**Issue by Choicelin** [FFans/lang-simplified-chinese#1]
我的版是0.1.0-beta.15 ，插件版本是0.1.0-beta.15.1

**Comment by Littlegolden** [comment]
请问在仪表盘启用简体中文语言包时，是否可以成功变成开启状态？
- 若否，看看 debug 模式下具体的报错内容？
- 若处于开启状态，在「常规」标签页中，检查默认语言是否是简体中文？

**Comment by Choicelin** [comment]
@Littlegolden 谢谢
